### PR TITLE
149 unsubscribe

### PR DESCRIPTION
**Pull request by MathieuNls**
To test and deploy

### CODE REVIEW

**Comment by MathieuNls** [comment]
On using `mc:edit` in Mailchimp template saved to mandrill...

```
Mathieu Nayrolles
Nov 1, 6:10 PM EDT

Chat started: 2016-11-01 09:27 PM UTC

(09:27:50 PM) Visitor 60662430 is now known as Mathieu Nayrolles.
(09:27:50 PM) Mathieu Nayrolles: Hi,

I have created Mailchimp templates containing `mc:edit` tag such as `<h1>Hey&nbsp;<span mc:edit="name">{{will be replaced}}</span>!</h1>`.

When I save my templates to mandrill, all the `mc:edit` tag are removed. Here's what the previous example been translated to in Mandrill:
` <h1>Hey&nbsp;<span>{{will be replaced}}</span>!</h1>`.

Consequently, the `template_content` variables sent via the API (https://mandrill.zendesk.com/hc/en-us/articles/205582497) don't match anything.

If I manually add back the `mc:edit` to the mandrill template, it works, the `span` is replaced, but that kind of defeat the purpose of mandrill being an addon of Mailchimp.

M
(09:28:52 PM) Customer Service: We apologize for keeping you waiting and appreciate your patience. Our operators are busy at the moment. One of our agents will be with you as soon as possible. 
(09:32:18 PM) *** Karnell joined the chat ***
(09:35:32 PM) Karnell: Hey M, I'd be happy to help. To make sure we are on the same page here you're looking to created custom coded HTML templates within Mailchimp to be used within the Mandrill application? However, when selecting these templates to be used in Mandrill the mc:edit parts of the template are being removed?
(09:36:52 PM) Mathieu Nayrolles: yes, I have created drag and drop templates in Mailchimp, then, using the action buttons, "Save to mandrill". The HTML that is sent to Mandrill doesn t contain the "mc:edit".
(09:39:42 PM) Karnell: Gotcha, the Mandrill application does support mc:edit regions, however editable images, repeatable areas, and variants don't work. Here is an article from the Mandrill Knowledge base on how to use editable content areas in Templates | https://mandrill.zendesk.com/hc/en-us/articles/205582497-Using-Editable-Content-Areas-in-Templates
(09:40:30 PM) Mathieu Nayrolles: That's the documentation I used and, unfortunately, it doesn't work.
(09:41:04 PM) Mathieu Nayrolles: Have a look at the template named "signup" linked to the mathieuNls account / Toolwatchapp organization
(09:42:10 PM) Mathieu Nayrolles: Btw, a simple "export as HTML" also remove the `mc:edit`tags
(09:45:39 PM) Karnell: When taking a look into the Template I can see all of the templates are Mailchimp Drag and drop templates. Do you have any custom coded templates with MC:edit tags in them that you'd be using within Mandrill?
(09:46:49 PM) Mathieu Nayrolles: No, I only used drag & drop template in order for my non-techy associates to be able to modify them.
(09:49:13 PM) Karnell: Gotcha, when using custom coded templates and exporting them to HTML they'd maintain their Mailchimp template language portions like the mc:edit tags and content. Drag and drop templates would not be expected to behave in this way or maintain their Mailchimp template language portions when exported.
(09:49:59 PM) Mathieu Nayrolles: mmmm, that's unfortunate.
(09:50:13 PM) Mathieu Nayrolles: Is their a way to convert d&d template to custom ?
(09:50:23 PM) Mathieu Nayrolles: there
(09:50:25 PM) Mathieu Nayrolles: *
(09:53:21 PM) Karnell: Sorry to be a bummer here Mathieu. However, there is not a way to convert a D&D template to a custom coded template without having to export the D&D then adding the MC template language back to the Templates HTML.
(09:56:11 PM) Mathieu Nayrolles: Ok, this should be in the documentation. I've wasted the afternoon on this :x. To which extent custom templates are editable by non-techy people ? Is there a way to modify the email text without having to go the HTML ?
(09:58:45 PM) Karnell: Yes, you'd be able to add an MC:edit you'd be able to create areas of the Content that can be edited within the Mailchimp Template builder for those we are not hip to making changes to the code | Create Editable Content Areas with MailChimp’s Template Language: http://eepurl.com/b2Q-Vv
(10:00:52 PM) Mathieu Nayrolles: I see. Problem is that I might end up with nested mc:edit. On the top level, a mc:edit for colleagues to be able to work, and, nested, the one I used for dynamic content. Is that ok?
(10:05:16 PM) Karnell: Hmmh, not sure about that one. It's best to test that kind of thing to be sure that it will work as desired.
(10:07:21 PM) Mathieu Nayrolles: Ok, thanks for your help. I'll test it tomorrow. Is the documentation open-source? Can I propose a change, so others will not have to reach out to you?
(10:08:55 PM) Karnell: It's not exactly open source but, the documentation on Mailchimp's template language is publically available for sure. If you'd like to pass along some feedback to our devs feel free to use our feedback from here | https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjVueiDyYjQAhWC5yYKHSNPBMIQFggpMAA&url=https%3A%2F%2Fmailchimp.com%2Fcontact%2Ffeedback%2F&usg=AFQjCNFYjiaZoyDWTKyPxR4p4tMrWm5mtw&bvm=bv.137132246,d.eWE
(10:09:09 PM) Karnell: Opps try this one |https://mailchimp.com/contact/feedback/
(10:10:07 PM) Mathieu Nayrolles: okok, thanks again
(10:10:22 PM) Karnell: You're welcome
(10:10:23 PM) Karnell: Cheers
(10:10:25 PM) *** Karnell left the chat ***
```

**Comment by MathieuNls** [comment]
On using mailchimp tag (con'd)

```
Marc Montagne
Hi,

I am trying to use merge tag in order to add dynamic content to my mandrill emails. I followed https://mandrill.zendesk.com/hc/en-us/articles/205582487-How-to-Use-Merge-Tags-to-Add-Dynamic-Content

In mandrill template id=signup I have some merge tags (e.g. *|NAME|* and *|UNSUB|*). Using the API I send values for them.

For example in API call api-detail?id=30529287.api_success.20161103152012677219, I have 

"template_name": "signup",
    "template_content": [
        {
            "name": "NAME",
            "content": "Mathieu"
        },
        {
            "name": "UNSUB",
            "content": "<a href='http://192.168.0.101/Unsubscribe/index/k11111111y'>here</a>"
        }
    ],

The tags, however, are not replaced in the email. 

Am I missing something ?

Thanks,
M.
Chat started
Please wait for an agent. There are currently 15 visitor(s) waiting to be served.
Customer Service
We apologize for keeping you waiting and appreciate your patience. Our operators are busy at the moment. One of our agents will be with you as soon as possible. 
Devin joined the chat
Devin
Hi there Marc
I'm happy to help
Marc Montagne
Hi
Can you see anything wrong ?
Devin
Looking into it now
Marc Montagne
ok, thanks
Devin
Still working on this
Marc Montagne
okok, no worries
Devin
When you say the tags are not replaced, can you elaborate about that?
Marc Montagne
I sent you a printscreen of the email related to the previous API call
In the email, I still have *|NAME|* and *|UNSUB|* where I should have the values I sent via the API
Devin
I understand. It's possible that templates like these will not actually populate with merge tag data until they are sent. I'm checking into that for you now.
Marc Montagne
I am sending the data inside the send_template API call.
Devin
Cool, thanks
Marc Montagne
Here's the full request/respons
Method: messages/send-template.json
Time: Nov 3, 2016 11:20 am
Call time: 453.0ms
IP: 192.222.151.60
User Agent: Mandrill-PHP/1.0.54
Full Request
{
    "template_name": "signup",
    "template_content": [
        {
            "name": "NAME",
            "content": "Mathieu"
        },
        {
            "name": "UNSUB",
            "content": "<a href='http://192.168.0.101/Unsubscribe/index/k11111111y'>here</a>"
        }
    ],
    "message": {
        "subject": "Welcome to Toolwatch! ⌚",
        "from_email": "hello@toolwatch.io",
        "from_name": "Toolwatch",
        "to": [
            {
                "email": "mathieu.nayrolles@gmail.com",
                "name": "Nayrolles Mathieu",
                "type": "to"
            }
        ],
        "headers": {
            "Reply-To": "hello@toolwatch.io"
        },
        "important": false,
        "track_opens": true,
        "track_clicks": true,
        "tags": [
            "signup"
        ],
        "google_analytics_campaign": "signup",
        "google_analytics_domains": [
            "toolwatch.io"
        ],
        "metadata": {
            "website": "toolwatch.io"
        }
    },
    "async": false,
    "ip_pool": "Main Pool",
    "send_at": "2016-11-01 16:20:11",
    "key": "72rd6UM9tLUpfbrGUct4sw"
}
Full Response
[
    {
        "email": "mathieu.nayrolles@gmail.com",
        "status": "sent",
        "_id": "c8df7c1dd46345a8a170a64b887f263b",
        "reject_reason": null
    }
]
Devin
Thanks, working with my technical team on this
Thanks for your patience. I was able to share this information with my technical team here and they are telling me that it wouldn't be expected for that data to display where the merge tags are when using a template like this. Templates do not render merge tag data dynamically. As a MailChimp Support Agent, I'm afraid I'll be limited in the support I can offer for Mandrill's templates, but if you need further assistance on this issue I would highly recommend reaching out to Mandrill Support directly at help@mandrill.com so they can take a closer look with you.
Marc Montagne
Ok :x. Since Mandrill and Mailchimp are the same company, I thought I was at the right place :x.
Thanls
Devin
My pleasure
```

**Comment by MathieuNls** [comment]
http://stackoverflow.com/questions/17263870/why-does-mandrill-not-recognize-my-merge-tags

**Comment by AlphonseJr** [comment]
@MathieuNls , I am assigned to this PR, is there something I should be checking?

**Comment by MathieuNls** [comment]
No, not yet

**Comment by AlphonseJr** [comment]
I've just signed up with a test account, I've correctly received the welcome email, I've FF26  (fast forward 26h) and correctly received the add_first_watch email, I then added a Jaeger-LeCoultre watch then FF52 and didn't receive neither the make_first_measure mail nor the add_watch_jlc

Did I miss something?

**Comment by AlphonseJr** [comment]
The emails on desktop do not have any margins : 

image

While we should have something like : 

image

Thanks Hook :)

**Comment by AlphonseJr** [comment]
For reference, the discussion I had with MailChimp support (I'll look into that today) : 

```

Chat started on 15 Nov 2016, 09:24 PM (GMT+0)
(09:24:00)	*** Marc Montagne joined the chat ***
(09:24:00)	Marc Montagne: Hello, We are using some templates on MailChimp, we visualize them and they look fine, and when we are receiving them through MailChimp, there are no margins, which results in a very poor display. My guess would be that Mandrill messes with the CSS. How can we fix that and render properly our mails? Thanks, Marc
(09:25:02)	Customer Service: We apologize for keeping you waiting and appreciate your patience. Our operators are busy at the moment. One of our agents will be with you as soon as possible.
(09:25:43)	*** Olivia joined the chat ***
(09:25:56)	Olivia: Hi Marc, I hope that you are doing well today.
(09:26:21)	Marc Montagne: Hi Olivia, I'm doing great and I'm sure I'll be even better when my issue will be fixed !
(09:26:40)	Olivia: Absolutely, and I'm going to do everything that I can to help out here. To clarify, are you sending in Mandrill add-on or from MailChimp?
(09:26:54)	Marc Montagne: from MailChimp
(09:26:57)	Marc Montagne: I'm editing a template
(09:27:05)	Marc Montagne: then I click on "Send to Mandrill"
(09:27:16)	Marc Montagne: which sends the mail on trigger
(09:27:25)	Marc Montagne: (i.e. when someone subscribes)
(09:31:00)	Olivia: To clarify, when using the "send to Mandrill" from within MailChimp, that would send the template to Mandrill, but wouldn't send the template automatically. You would need to log into Mandrill in order to send that template off.
(09:31:55)	Olivia: However, concerning the CSS, I can try to take a look into this on my end. It's important to mention that although technical support agents are experts of the MailChimp application, we are limited on our level of expertise concerning customized coding.
(09:33:21)	Marc Montagne: I'd appreciate that! And we are not doing anything fancy regarding customization. When me "send to Mandrill" this sends the HTML to Mandrill to be used whenever the email is triggered
(09:33:40)	Marc Montagne: and there are different emails depending on the trigger
(09:33:51)	Olivia: Absolutely, may I ask what is the name of the template in MailChimp?
(09:34:03)	Marc Montagne: like the "lost password email" will be sent whenever a user requests a new password and so on
(09:34:04)	Marc Montagne: sure
(09:34:12)	Olivia: Also can I request a screenshot of how that template appears in Mandrill so that I may review that on my end?
(09:34:13)	Marc Montagne: "signup"
(09:34:42)	Marc Montagne: is the name of the template we are using whenever a user subscribes and therefore receives a welcome email
(09:35:01)	Marc Montagne: sure, can I directly send the screenshot in this chat window ?
(09:36:24)	Olivia: Thank you, Marc. Yes, that screenshot can be shared by dragging the image into the chat window and then pressing enter to release it to me.
(09:38:16)	Marc Montagne: Visitor uploaded: mailchimp-template.JPG URL: https://v2uploads.zopim.io/3/b/6/3b6ziEnZVB74oBc8AtnqB7kdH8QS4Zst/4dkbapo3keYgsUFe-cLfoFBndF3UFOy-e8264bc0b117d994c32b61ac0667dd1744943834.jpg Type: image/jpeg Size: 75864 Thumb: https://v2uploads.zopim.io/3/b/6/3b6ziEnZVB74oBc8AtnqB7kdH8QS4Zst/4dkbapo3keYgsUFe-cLfoFBndF3UFOy-e8264bc0b117d994c32b61ac0667dd1744943834.thumb.jpg
(09:38:44)	Marc Montagne: Visitor uploaded: email-received---no-margins.JPG URL: https://v2uploads.zopim.io/3/b/6/3b6ziEnZVB74oBc8AtnqB7kdH8QS4Zst/4dkbapo3keYgsUFe-cLfoFBndF3UFOy-b3d3746bbfb36b871733ce1462fce42bcac4c670.jpg Type: image/jpeg Size: 89795 Thumb: https://v2uploads.zopim.io/3/b/6/3b6ziEnZVB74oBc8AtnqB7kdH8QS4Zst/4dkbapo3keYgsUFe-cLfoFBndF3UFOy-b3d3746bbfb36b871733ce1462fce42bcac4c670.thumb.jpg
(09:38:54)	Olivia: Thank you so much
(09:38:58)	Marc Montagne: The first one is the preview from MailChimp
(09:39:03)	Marc Montagne: and the second one is the one received
(09:39:46)	Olivia: I see what you mean, just a moment while I look into that.
(09:39:56)	Marc Montagne: Thank you so much Olivia
(09:41:16)	Olivia: You're welcome, Marc!
(09:46:36)	Olivia: Ok, so I'm seeing that the content appears to have been pasted in from an outside source, and this appears to be what's causing for that formatting to be off. This is usually the case when content has been placed inside of a campaign from a source such as Word or Publisher. We're able to render the code without issue in MailChimp, however, when viewed outside of the account, there are likely to be issues with rendering the background coding, so formatting issues will usually occur. In cases such as this, I recommend pasting in text using our rich text or plain text editor tools: http://screencast.com/t/fa32hWYr. Also, this resource guide can be referenced for more insight on using this tool: Prevent Formatting Problems with Paste from Rich Text: http://eepurl.com/buaowT.
(09:49:15)	Marc Montagne: Okay I see
(09:49:29)	Marc Montagne: and indeed the content have been copied
(09:49:51)	Marc Montagne: is there a way of getting rid of the formatting without redoing every all again ?
(09:52:17)	Marc Montagne: everything*
(09:53:03)	Olivia: You could try using the clear styles tool, and then test this out from Mandrill. However, the best tool to use would be our plain or rich text and then copy and repaste the content back into the template using either tool. Here is where to locate the clear styles tool: http://screencast.com/t/tsFvKh7XKI
(09:54:58)	Marc Montagne: Okay, I'll do that tomorrow (it's getting late here in Europe)! Thank you so much for your help and have a great day Marc
(09:55:37)	Olivia: You're welcome, Marc! I hope that you have a great day too, and please do reach back out should you have any other quesitons.
(09:55:42)	Olivia: question*
(09:58:18)	*** Olivia left the chat ***
(10:30:51)	*** Marc Montagne left the chat ***
```

**Comment by AlphonseJr** [comment]
Unsubscribe et mails : ok !

Il nous reste juste le formatage à régler avant de pouvoir merge.

**Pull request merged**
